- name: Hetzner Cloud VPS Setup
  hosts: localhost
  vars_files:
    - vars/secrets.yml
  gather_facts: no
  tasks:
    - name: Create server
      hcloud_server:
        name: hbsd-gitea
        api_token: "{{ hetzner_cloud_api_key }}"
        location: fsn1
        server_type: cx11
        image: "25953421"
        ssh_keys:
          - jonas@notamac
        state: present
      register: deployed
    - name: Add server to inventory
      add_host:
        hostname: hbsd-gitea
        groupname: hcloud
        ansible_host: "{{ deployed.hcloud_server.ipv4_address }}"
        ansible_user: root
        ansible_python_interpreter: /usr/local/bin/python3
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
        hcloud_server_name: "{{ deployed.hcloud_server.name }}"
    - name: Wait for server to start up
      delegate_to: hbsd-gitea
      wait_for_connection:
        timeout: 200

- name: gitea server configuration
  hosts: hbsd-gitea
  vars_files:
    - vars/secrets.yml
  vars:
    disable_gitea_registration: "true"
    gitea_app_ini: /usr/local/etc/gitea/conf/app.ini
  tasks:
    - name: update OS if required
      command: /usr/sbin/hbsd-update
    - name: update packages
      pkgng:
        name: "*"
        state: latest

    - name: install gitea
      pkgng:
        name: gitea
        state: present
    - name: install caddy
      pkgng:
        name: caddy
        state: present
    - name: install caddyfile
      copy:
        src: etc/Caddyfile
        dest: /usr/local/etc/caddy/Caddyfile

    - name: ensure secret key in gitea config
      ini_file:
        path: "{{ gitea_app_ini }}"
        create: no
        section: security
        option: SECRET_KEY
        value: "{{ gitea_secret_key }}"
    - name: disable gitea registration
      ini_file:
        path: "{{ gitea_app_ini }}"
        create: no
        section: service
        option: DISABLE_REGISTRATION
        value: "{{ disable_gitea_registration }}"
      notify: restart gitea
    - name: set default gitea theme
      ini_file:
        path: "{{ gitea_app_ini }}"
        create: no
        section: ui
        option: DEFAULT_THEME
        value: arc-green
      notify: restart gitea

    - name: enable and start gitea service
      service:
        name: gitea
        enabled: yes
        state: started
    - name: enable and start caddy service
      service:
        name: caddy
        enabled: yes
        state: started

    - name: install pf config
      template:
        src: templates/pf.conf.j2
        dest: /etc/pf.conf
        validate: /sbin/pfctl -nf %s
      notify: restart pf
    - name: enable and start pf
      service:
        name: pf
        enabled: yes
        state: started

  handlers:
    - name: restart gitea
      service:
        name: gitea
        state: restarted
    - name: restart pf
      service:
        name: pf
        state: restarted
