---
- name: preview config
  when: ansible_check_mode
  debug:
    msg: "pf config: {{ lookup('template', 'pf.conf.j2') }}"

- name: Ensure config is in place
  template:
    src: pf.conf.j2
    dest: /etc/pf.conf
    validate: /sbin/pfctl -nf %s
  notify: reload config

# Note: This task will cause the connection to drop when run for the first time,
# so it takes a couple of minutes per host to complete.
- name: Ensure service is enabled and running
  service:
    name: pf
    enabled: yes
    state: started
