---
# This playbook contains basic HardenedBSD maintenance stuff; packages and OS upgrades

- name: Upgrade the OS to the latest build
  hbsd-update:
    boot_env: yes
  register: result
- name: Reboot after upgrade
  when: result.changed
  reboot:
    post_reboot_delay: 60

- name: Update packages
  pkgng:
    name: "*"
    state: latest
    autoremove: yes
